// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "GPS_GPS_t.h"

static int __GPS_GPS_t_hash_computed;
static uint64_t __GPS_GPS_t_hash;

uint64_t __GPS_GPS_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __GPS_GPS_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__GPS_GPS_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xdaf02f5cf4181638LL
         + __int64_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __GPS_GPS_t_get_hash(void)
{
    if (!__GPS_GPS_t_hash_computed) {
        __GPS_GPS_t_hash = (int64_t)__GPS_GPS_t_hash_recursive(NULL);
        __GPS_GPS_t_hash_computed = 1;
    }

    return __GPS_GPS_t_hash;
}

int __GPS_GPS_t_encode_array(void *buf, int offset, int maxlen, const GPS_GPS_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].latitude), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].longitude), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].south), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].north), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].east), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].west), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int GPS_GPS_t_encode(void *buf, int offset, int maxlen, const GPS_GPS_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __GPS_GPS_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __GPS_GPS_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __GPS_GPS_t_encoded_array_size(const GPS_GPS_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __double_encoded_array_size(&(p[element].latitude), 1);

        size += __double_encoded_array_size(&(p[element].longitude), 1);

        size += __int8_t_encoded_array_size(&(p[element].south), 1);

        size += __int8_t_encoded_array_size(&(p[element].north), 1);

        size += __int8_t_encoded_array_size(&(p[element].east), 1);

        size += __int8_t_encoded_array_size(&(p[element].west), 1);

    }
    return size;
}

int GPS_GPS_t_encoded_size(const GPS_GPS_t *p)
{
    return 8 + __GPS_GPS_t_encoded_array_size(p, 1);
}

int __GPS_GPS_t_decode_array(const void *buf, int offset, int maxlen, GPS_GPS_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].latitude), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].longitude), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].south), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].north), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].east), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].west), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __GPS_GPS_t_decode_array_cleanup(GPS_GPS_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __double_decode_array_cleanup(&(p[element].latitude), 1);

        __double_decode_array_cleanup(&(p[element].longitude), 1);

        __int8_t_decode_array_cleanup(&(p[element].south), 1);

        __int8_t_decode_array_cleanup(&(p[element].north), 1);

        __int8_t_decode_array_cleanup(&(p[element].east), 1);

        __int8_t_decode_array_cleanup(&(p[element].west), 1);

    }
    return 0;
}

int GPS_GPS_t_decode(const void *buf, int offset, int maxlen, GPS_GPS_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __GPS_GPS_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __GPS_GPS_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int GPS_GPS_t_decode_cleanup(GPS_GPS_t *p)
{
    return __GPS_GPS_t_decode_array_cleanup(p, 1);
}

int __GPS_GPS_t_clone_array(const GPS_GPS_t *p, GPS_GPS_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __double_clone_array(&(p[element].latitude), &(q[element].latitude), 1);

        __double_clone_array(&(p[element].longitude), &(q[element].longitude), 1);

        __int8_t_clone_array(&(p[element].south), &(q[element].south), 1);

        __int8_t_clone_array(&(p[element].north), &(q[element].north), 1);

        __int8_t_clone_array(&(p[element].east), &(q[element].east), 1);

        __int8_t_clone_array(&(p[element].west), &(q[element].west), 1);

    }
    return 0;
}

GPS_GPS_t *GPS_GPS_t_copy(const GPS_GPS_t *p)
{
    GPS_GPS_t *q = (GPS_GPS_t*) malloc(sizeof(GPS_GPS_t));
    __GPS_GPS_t_clone_array(p, q, 1);
    return q;
}

void GPS_GPS_t_destroy(GPS_GPS_t *p)
{
    __GPS_GPS_t_decode_array_cleanup(p, 1);
    free(p);
}

int GPS_GPS_t_publish(lcm_t *lc, const char *channel, const GPS_GPS_t *p)
{
      int max_data_size = GPS_GPS_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = GPS_GPS_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _GPS_GPS_t_subscription_t {
    GPS_GPS_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void GPS_GPS_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    GPS_GPS_t p;
    memset(&p, 0, sizeof(GPS_GPS_t));
    status = GPS_GPS_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding GPS_GPS_t!!!\n", status);
        return;
    }

    GPS_GPS_t_subscription_t *h = (GPS_GPS_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    GPS_GPS_t_decode_cleanup (&p);
}

GPS_GPS_t_subscription_t* GPS_GPS_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    GPS_GPS_t_handler_t f, void *userdata)
{
    GPS_GPS_t_subscription_t *n = (GPS_GPS_t_subscription_t*)
                       malloc(sizeof(GPS_GPS_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 GPS_GPS_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg GPS_GPS_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int GPS_GPS_t_subscription_set_queue_capacity (GPS_GPS_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int GPS_GPS_t_unsubscribe(lcm_t *lcm, GPS_GPS_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe GPS_GPS_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

