// Generated by gencpp from file kingfisher_msgs/GPS.msg
// DO NOT EDIT!


#ifndef KINGFISHER_MSGS_MESSAGE_GPS_H
#define KINGFISHER_MSGS_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kingfisher_msgs
{
template <class ContainerAllocator>
struct GPS_
{
  typedef GPS_<ContainerAllocator> Type;

  GPS_()
    : GPS_receivedTime(0.0)
    , GPS_latitude(0.0)
    , GPS_longitude(0.0)  {
    }
  GPS_(const ContainerAllocator& _alloc)
    : GPS_receivedTime(0.0)
    , GPS_latitude(0.0)
    , GPS_longitude(0.0)  {
  (void)_alloc;
    }



   typedef double _GPS_receivedTime_type;
  _GPS_receivedTime_type GPS_receivedTime;

   typedef double _GPS_latitude_type;
  _GPS_latitude_type GPS_latitude;

   typedef double _GPS_longitude_type;
  _GPS_longitude_type GPS_longitude;




  typedef boost::shared_ptr< ::kingfisher_msgs::GPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kingfisher_msgs::GPS_<ContainerAllocator> const> ConstPtr;

}; // struct GPS_

typedef ::kingfisher_msgs::GPS_<std::allocator<void> > GPS;

typedef boost::shared_ptr< ::kingfisher_msgs::GPS > GPSPtr;
typedef boost::shared_ptr< ::kingfisher_msgs::GPS const> GPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kingfisher_msgs::GPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kingfisher_msgs::GPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kingfisher_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kingfisher_msgs': ['/home/usydrowbot/catkin_ws/src/kingfisher_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kingfisher_msgs::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kingfisher_msgs::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kingfisher_msgs::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kingfisher_msgs::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kingfisher_msgs::GPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kingfisher_msgs::GPS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kingfisher_msgs::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f1b89d4744f53db1d3b5b2ee7066ef1";
  }

  static const char* value(const ::kingfisher_msgs::GPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f1b89d4744f53dbULL;
  static const uint64_t static_value2 = 0x1d3b5b2ee7066ef1ULL;
};

template<class ContainerAllocator>
struct DataType< ::kingfisher_msgs::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kingfisher_msgs/GPS";
  }

  static const char* value(const ::kingfisher_msgs::GPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kingfisher_msgs::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 GPS_receivedTime\n\
float64 GPS_latitude\n\
float64 GPS_longitude\n\
";
  }

  static const char* value(const ::kingfisher_msgs::GPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kingfisher_msgs::GPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.GPS_receivedTime);
      stream.next(m.GPS_latitude);
      stream.next(m.GPS_longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kingfisher_msgs::GPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kingfisher_msgs::GPS_<ContainerAllocator>& v)
  {
    s << indent << "GPS_receivedTime: ";
    Printer<double>::stream(s, indent + "  ", v.GPS_receivedTime);
    s << indent << "GPS_latitude: ";
    Printer<double>::stream(s, indent + "  ", v.GPS_latitude);
    s << indent << "GPS_longitude: ";
    Printer<double>::stream(s, indent + "  ", v.GPS_longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINGFISHER_MSGS_MESSAGE_GPS_H
